---
title: "Unidad 0. Manual de instalación de R y RStudio"
subtitle: "Del Curso introductorio al lenguaje de programación R orientado al análisis cuantitativo en Ciencias Sociales"
author: "Por Sarahí Aguilar"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br/>

[↩ Página principal del curso](index.html)

<br/>

## Inicio

> #### 🚀 **Objetivo**  
Que el estudiante tenga un entorno de desarrollo de R en RStudio listo en su equipo de cómputo propio antes del inicio del curso.

> #### 📣 **Aclaraciones y consideraciones importantes** 
* Esta unidad debe ser completada por el estudiante antes del inicio del curso con el equipo de cómputo a utilizar en el mismo.
* Con el fin de facilitar la resolución de problemas durante el curso, la profesora y todos los estudiantes trabajarán con la misma versión de R (4.0.5) y RStudio (cualquier subversión de la 1.4.1). Por ello, esta unidad debe ser completada incluso si el estudiante había previamente instalado R y/o RStudio en el mismo equipo de cómputo. 

<br/>

## 0.1. Instalación de R 4.1.0
1. Entrar a la [página oficial de R](https://www.r-project.org/). 
2. En la sección titulada "Getting Started", dar click sobre ["download R"](https://cran.r-project.org/mirrors.html).
3. Buscar el espejo del ITAM y dar click sobre [https://cran.itam.mx/](https://cran.itam.mx/).   
Para los fines de este curso, usted no requiere conocer el concepto de "espejo". 
4. Con base en el sistema operativo de su equipo de cómputo, dar click sobre "Download R for Linux (Debian, Fedora/Redhat, Ubuntu)", "Download R for macOS" o "Download R for Windows" y siga las instrucciones de instalación **sin modificar los parámetros ya establecidos por defecto**.  
Para el caso de equipos de cómputo con Windows como sistema operativo:
    + Dar click en "Download R for Windows".
    + Dar click sobre el subdirectorio "base". 
    + Dar click sobre ["Download R 4.1.0 for Windows"](https://cran.itam.mx/bin/windows/base/R-4.1.0-win.exe). 
    + Se iniciará la descarga de un archivo llamado "R-4.1.0-win". Una vez terminada la descarga, ejecutar (dar click sobre) el archivo descargado. 
    + Se abrirá el instalador de R sobre el cuál deberá dar click en "Continuar" en cada ocasión **sin modificar los parámetros ya establecidos por defecto**. 


<br/>

## 0.2. Instalación de RStudio 1.4.1